// Mock data store - simulates a backend
import { addDays, subDays, setHours, setMinutes } from 'date-fns'

const today = new Date()

export const mockPatients = [
  {
    id: '1',
    name: 'Ana Clara Souza',
    birthDate: '1990-03-15',
    phone: '(11) 99999-1111',
    whatsapp: '(11) 99999-1111',
    email: 'ana.clara@email.com',
    address: 'Rua das Flores, 123 - São Paulo, SP',
    notes: 'Paciente com ansiedade generalizada. Prefere sessões às terças.',
    status: 'active',
    photo: null,
    createdAt: subDays(today, 120).toISOString(),
  },
  {
    id: '2',
    name: 'Bruno Martins',
    birthDate: '1985-07-22',
    phone: '(11) 98888-2222',
    whatsapp: '(11) 98888-2222',
    email: 'bruno.martins@email.com',
    address: 'Av. Paulista, 456 - São Paulo, SP',
    notes: 'Terapia cognitivo-comportamental. Sessões semanais.',
    status: 'active',
    photo: null,
    createdAt: subDays(today, 90).toISOString(),
  },
  {
    id: '3',
    name: 'Carla Fernandes',
    birthDate: '1995-11-08',
    phone: '(11) 97777-3333',
    whatsapp: '(11) 97777-3333',
    email: 'carla.f@email.com',
    address: 'Rua Augusta, 789 - São Paulo, SP',
    notes: 'Depressão leve. Acompanhamento quinzenal.',
    status: 'active',
    photo: null,
    createdAt: subDays(today, 60).toISOString(),
  },
  {
    id: '4',
    name: 'Diego Alves',
    birthDate: '1988-05-30',
    phone: '(11) 96666-4444',
    whatsapp: '(11) 96666-4444',
    email: 'diego.alves@email.com',
    address: 'Rua Oscar Freire, 321 - São Paulo, SP',
    notes: 'Fobia social. Progresso significativo.',
    status: 'inactive',
    photo: null,
    createdAt: subDays(today, 200).toISOString(),
  },
  {
    id: '5',
    name: 'Eduarda Lima',
    birthDate: '2000-01-14',
    phone: '(11) 95555-5555',
    whatsapp: '(11) 95555-5555',
    email: 'edu.lima@email.com',
    address: 'Rua Consolação, 654 - São Paulo, SP',
    notes: 'Transtorno de ansiedade. Sessões semanais.',
    status: 'active',
    photo: null,
    createdAt: subDays(today, 30).toISOString(),
  },
]

const makeDate = (daysOffset, hour, minute = 0) => {
  const d = daysOffset === 0 ? new Date(today) : daysOffset > 0 ? addDays(today, daysOffset) : subDays(today, Math.abs(daysOffset))
  d.setHours(hour, minute, 0, 0)
  return d.toISOString()
}

export const mockAppointments = [
  {
    id: 'a1',
    patientId: '1',
    date: makeDate(0, 9),
    duration: 50,
    modality: 'presencial',
    meetingLink: '',
    status: 'confirmed',
    notes: 'Sessão de acompanhamento semanal.',
  },
  {
    id: 'a2',
    patientId: '2',
    date: makeDate(0, 10),
    duration: 50,
    modality: 'online',
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    status: 'scheduled',
    notes: '',
  },
  {
    id: 'a3',
    patientId: '3',
    date: makeDate(0, 14),
    duration: 50,
    modality: 'presencial',
    meetingLink: '',
    status: 'confirmed',
    notes: 'Retorno após quinzena.',
  },
  {
    id: 'a4',
    patientId: '5',
    date: makeDate(0, 16),
    duration: 50,
    modality: 'online',
    meetingLink: 'https://zoom.us/j/123456789',
    status: 'scheduled',
    notes: '',
  },
  {
    id: 'a5',
    patientId: '1',
    date: makeDate(1, 9),
    duration: 50,
    modality: 'presencial',
    meetingLink: '',
    status: 'scheduled',
    notes: '',
  },
  {
    id: 'a6',
    patientId: '2',
    date: makeDate(1, 11),
    duration: 50,
    modality: 'online',
    meetingLink: 'https://meet.google.com/xyz-uvwx-yz',
    status: 'scheduled',
    notes: '',
  },
  {
    id: 'a7',
    patientId: '4',
    date: makeDate(-1, 10),
    duration: 50,
    modality: 'presencial',
    meetingLink: '',
    status: 'done',
    notes: 'Sessão realizada com sucesso.',
  },
  {
    id: 'a8',
    patientId: '3',
    date: makeDate(-2, 14),
    duration: 50,
    modality: 'presencial',
    meetingLink: '',
    status: 'missed',
    notes: 'Paciente não compareceu.',
  },
  {
    id: 'a9',
    patientId: '5',
    date: makeDate(2, 15),
    duration: 50,
    modality: 'online',
    meetingLink: 'https://zoom.us/j/987654321',
    status: 'scheduled',
    notes: '',
  },
  {
    id: 'a10',
    patientId: '1',
    date: makeDate(3, 9),
    duration: 50,
    modality: 'presencial',
    meetingLink: '',
    status: 'scheduled',
    notes: '',
  },
]

export const mockSettings = {
  workDays: [1, 2, 3, 4, 5],
  startHour: 7,
  endHour: 22,
  lunchStart: 12,
  lunchEnd: 13,
  intervalBetween: 10,
  defaultDuration: 50,
  blockedDates: [],
  holidays: [],
}

export const mockUser = {
  id: 'u1',
  name: 'Dra. Isabela Pedrozo Silva',
  email: 'isabela@psicologa.com',
  crp: 'CRP 06/123456',
  photo: null,
}
